### PR TITLE
Add additional capabilities for specifying entities with target time

### LINKED ISSUE #57: Feature request - multiple target sets
Would it be possible to allow multiple target sets to be highlighted by this card?  I current have three which I use.  One from 00:00 to 06:00, one from 12:00 to 16:00 and one from 16:00 to 16:00.

### LINKED ISSUE #64: Documentation : Link to Target Rate Sensor documentation gives 404
As the title says, broken link in the target rate sensor documentation.
Try this for the BottlecapDave pages -
https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/target_rate/

### PR DESCRIPTION
**Pull request by alinbalutoiu**
This PR adds additional capabilities to highlight target times:
- It makes the background color customizable
- It allows you to set a prefix for the date (useful if you want to add emojis for example)
- It makes possible to add as many target times as you want

It does also mean it's breaking previous configurations since `targetTimesEntity` and `targetTimesEntity2` is no longer supported.

The migration is pretty straightforwad, from:
```yaml
targetTimesEntity: binary_sensor.octopus_energy_target_rate3
targetTimesEntity2: binary_sensor.octopus_energy_target_rate4
```
to:
```yaml
targetTimesEntities:
  binary_sensor.octopus_energy_target_rate3:
  binary_sensor.octopus_energy_target_rate4:
```

Finally, here's a picture on how that looks like.

image

Addresses the following:
- Fixes #64 
- Fixes #57

### CODE REVIEW

**Comment by corvus2606** [comment]
good solution, better than mine 👍

**Comment by lozzd** [comment]
This is very nice! 

One minor thing, your example config section (and great screenshots on this PR for that matter) - could you move that in to/replace the content under the "advanced configurations" section further down in the README?

I'll need to write up a note about the breaking change for the release notes but that's fine.

**Comment by alinbalutoiu** [comment]
I've updated the README, let me know if that works.

I had a separate text card in home assistant which was showing the target time intervals, but this is making life so much easier, thanks for adding support for it initially!

**Comment by lozzd** [comment]
Thanks very much! love the feature. This is now released in v0.6.0 with the note about the breaking change in configuration format.

**Pull request merged**
